### ISSUE TITLE
Excuse me, where could I get the baseline?

### ISSUE THREAD

**Issue by Rollingbutter** [zouguojian/Traffic-speed-prediction#14]
Sorry to bother. I'd like to ask where could I get the baseline?

**Comment by zouguojian** [comment]
> Sorry to bother. I'd like to ask where could I get the baseline?

You can get the baselines in the following link,

https://github.com/zouguojian/Traffic-speed-prediction/tree/main/3S-TBLN/baselines.

Thanks. If you have any other questions, please do not hesitate to contact me.

All the Best,
Guojian

**Comment by Rollingbutter** [comment]
> > Sorry to bother. I'd like to ask where could I get the baseline?
> 
> You can get the baselines in the following link,
> 
> https://github.com/zouguojian/Traffic-speed-prediction/tree/main/3S-TBLN/baselines.
> 
> Thanks. If you have any other questions, please do not hesitate to contact me.
> 
> All the Best, Guojian

Thank you very much!

**Comment by zouguojian** [comment]
> > > Sorry to bother. I'd like to ask where could I get the baseline?
> > 
> > 
> > You can get the baselines in the following link,
> > https://github.com/zouguojian/Traffic-speed-prediction/tree/main/3S-TBLN/baselines.
> > Thanks. If you have any other questions, please do not hesitate to contact me.
> > All the Best, Guojian
> 
> Thank you very much!
